name: Go

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ * ]

jobs:

  presubmit:
    name: CI Presubmits
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test github.com/downflux/go-kd
      run: go test github.com/downflux/go-kd/... -timeout=15m

on:
  push:
    branches: [ main ]

jobs:

  presubmit:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build github.com/downflux/go-kd
      run: go build -v github.com/downflux/go-kd/...

    - name: Build github.com/downflux/go-kd
      run: go vet github.com/downflux/go-kd/...

    - name: Test github.com/downflux/go-kd
      run: go test -v github.com/downflux/go-kd/... -run ^$ -bench . -benchmem -timeout=60m
