name: CI Presubmits

on:
  push:
    branches: [ "*" ]

jobs:

  presubmit:
    name: CI Presubmits
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test github.com/downflux/go-kd
      run: go test github.com/downflux/go-kd/... -timeout=15m
